# Client-facing AP on a second radio (wlan1) while wlan0 is mesh backhaul.
# LEGAL: unlicensed Wi-Fi only; verify national rules. Not free commercial broadband.
interface=wlan1
driver=nl80211
ssid=SkyCache-Local
hw_mode=g
channel=11
ieee80211n=1
wmm_enabled=1
# Prefer WPA2 in most deployments after training day:
# wpa=2
# wpa_passphrase=change-me-village
# wpa_key_mgmt=WPA-PSK
# rsn_pairwise=CCMP
